version: "3.8"

services:
  vector:
    image: timberio/vector:0.51.0-debian
    volumes:
      - ./ingest/config/vector.yaml:/etc/vector/vector.yaml
    ports:
      - "514:514/udp"   # route_syslog
      - "515:515/udp"   # firewall_syslog
      - "9000:9000"     # json_syslog
      - "9001:9001"     # M365_syslog
      - "9002:9002"     # Crowdstrike
      - "9003:9003"     # AWS_CT
      - "9004:9004"
    restart: always

  backend:
    build: ./backend
    restart: on-failure
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    restart: always
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:     
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysql
      POSTGRES_DB: logs_user
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1 FROM users LIMIT 1'"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
